function [line_cons] = create_ineq_linelimit(Psi_u_vvcos,Psi_l_vvcos,Psi_u_vvsin,Psi_l_vvsin,Psi_u_vv,Psi_l_vv,p_line_fr_u,q_line_fr_u,p_line_to_u,q_line_to_u,M_line_plus,M_line_minus,Nbus)
    line_cons1 =  M_line_plus *[zeros(2*Nbus,1);Psi_u_vvcos;Psi_u_vvsin;Psi_u_vv] +...
        M_line_minus*[zeros(2*Nbus,1);Psi_l_vvcos;Psi_l_vvsin;Psi_l_vv] -...
        [p_line_fr_u;p_line_to_u;q_line_fr_u;q_line_to_u];%<=0
    line_cons2 = -M_line_minus*[zeros(2*Nbus,1);Psi_u_vvcos;Psi_u_vvsin;Psi_u_vv] -...
        M_line_plus *[zeros(2*Nbus,1);Psi_l_vvcos;Psi_l_vvsin;Psi_l_vv] -...
        [p_line_fr_u;p_line_to_u;q_line_fr_u;q_line_to_u];%<=0

    line_cons = vertcat(line_cons1,line_cons2);
    %8*Nbranch
end

